### PR TITLE
Settings page, Classes page, time enter page, Redux layer update

### PR DESCRIPTION
**Pull request by deadlocked247**
image
image

### CODE REVIEW

**Comment by kosigz** [comment]
Amazing! 

> Ship ship ship.

**Review by kosigz — APPROVED** [review]
Looks good. Everything seems well structured and well tested.

**Comment by annuraju** [comment]
Just to remind you guys!! Make sure you're following the rules of smart
commits !! Else we wont be able to see those git commits against your jira
tickets.

**Comment by deadlocked247** [comment]
@annuraju What do you mean by that? Could you explain?

**Comment by annuraju** [comment]
Hi,

Did you do this?

https://piazza.com/class/isuxnc0ksk43og?cid=139

I believe you have added me to your list but haven't filled out the sheet
yet and I have not able to setup your JIRA-Git link.

Could you get to this asap?

Thanks,
Sri

**Pull request merged**
